### ISSUE TITLE
Using features-json for in-vim previews

### ISSUE THREAD

**Issue by tmcw** [zoeesilcock/vim-caniuse#1]
Seems like it'd be possible to use [caniuse's source](https://github.com/Fyrd/caniuse/blob/master/features-json/geolocation.json) and [webapi](https://github.com/mattn/webapi-vim) to show caniuse results directly in vim?

**Comment by zoeesilcock** [comment]
That's a great idea and it sounds doable. I'll look into this once I've solved some smaller issues that I have in the pipeline. Thanks for the suggestion!

**Comment by tmcw** [comment]
Closing as idle
